# Generated by Django 3.1.8 on 2021-04-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210413_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='postcode',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='town',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
